# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def beer_to_batch( apps, schema_editor ):
    Batch = apps.get_model( 'beer', 'Batch' )
    if Batch.objects.count() <= 0:
        return

    # If there are no beers defined then we must delete
    # any existing batches
    Beer = apps.get_model( 'beer', 'Beer' )
    if Beer.objects.count() <= 0:
        Batch.objects.delete_all()
    else:
        for b in Batch.objects.all():
            if b.packages.count() <= 0:
                b.delete()
            else:
                b.beer = b.packages.first().beer
                b.save()

class Migration( migrations.Migration ):
    dependencies = [
        ( 'beer', '0001_initial' ),
    ]

    operations = [
        migrations.AlterField( 
            model_name = 'package',
            name = 'batch',
            field = models.ForeignKey( on_delete = django.db.models.deletion.CASCADE, related_name = 'packages', to = 'beer.Batch' ),
        ),
        migrations.AddField( 
            model_name = 'batch',
            name = 'beer',
            field = models.ForeignKey( null = True, blank = True, on_delete = django.db.models.deletion.CASCADE, related_name = 'batches', to = 'beer.Beer' ),
            preserve_default = False,
        ),
        migrations.RunPython( 
            beer_to_batch
        ),
        migrations.AlterField( 
             model_name = 'batch',
             name = 'beer',
             field = models.ForeignKey( null = False, blank = False, on_delete = django.db.models.deletion.CASCADE, related_name = 'batches', to = 'beer.Beer' ),
        ),
        migrations.RemoveField( 
            model_name = 'package',
            name = 'beer',
        )
    ]
